# ----------------------------------------
# 1.Data
# ----------------------------------------
data:
  # grid definite
  cell_size   : 0.001      # about 
  min_lat     : 39.847733   # save for calculating w (calulate from grid_stats.py)
  min_lon     : 115.6791
  fixed_window: 18         # w (calulate from scan_w.py)
  num_cells_x : 37         # lon grid count = pad_idx + 1
  num_cells_y : 37         # lat grid count = pad_idx + 1
  pad_idx     : 36         # 2*w+1

  # 檔案路徑
  dataset_dir : data/datasets   # csv files directory
  skip_list   : data/notBeijing.txt #files to skip

# ----------------------------------------
# 2.Model
# ----------------------------------------
model:
  embedding:
    dim        : 64         # (= D)
    mode       : concat     # concat | sum
    dropout    : 0.1
    layernorm  : true

  compressor:               # ⇐ Transformer Encoder
    layers     : 4
    heads      : 8
    ffn_dim    : 256
    dropout    : 0.1

  constructor:              # ⇐ Transformer Decoder
    layers     : 4
    heads      : 8
    ffn_dim    : 256
    dropout    : 0.1

  bottleneck:
    compression_ratio: 0.3  # 0.3 = 30% of input sequence length
  loss: mse                 # mse | l1
  max_seq_len: 2048
  local_window: 18          # constructor used (w)

# ----------------------------------------
# 3.Training
# ----------------------------------------
training:
  split_ratio : [0.7, 0.1, 0.2]   # train / val / test
  batch_size  : 16
  lr          : 1.0e-4
  epochs      : 50
  num_workers : 0
  seed        : 42
