# ----------------------------------------
# 1.Data
# ----------------------------------------
data:
  # grid definite
  cell_size   : 0.0001      # about 11m
  min_lat     : 39.847733
  min_lon     : 115.6791
  num_cells_x : 11361       # lon grid count
  num_cells_y : 7164        # lat grid count

  # 檔案路徑
  dataset_dir : data/datasets   # csv files directory
  skip_list   : data/notBeijing.txt #files to skip

# ----------------------------------------
# 2.Model
# ----------------------------------------
model:
  embedding:
    dim        : 64         # (= D)
    mode       : concat     # concat | sum
    dropout    : 0.1
    layernorm  : true

  compressor:               # ⇐ Transformer Encoder
    layers     : 4
    heads      : 8
    ffn_dim    : 512
    dropout    : 0.1

  constructor:              # ⇐ Transformer Decoder
    layers     : 4
    heads      : 8
    ffn_dim    : 512
    dropout    : 0.1

  bottleneck:
    compression_ratio: 0.3  # 0.3 = 30% of input sequence length
  loss: mse                 # mse | l1
  max_seq_len: 2048

# ----------------------------------------
# 3.Training
# ----------------------------------------
training:
  split_ratio : [0.7, 0.1, 0.2]   # train / val / test
  batch_size  : 16
  lr          : 1.0e-4
  epochs      : 50
  num_workers : 0
  seed        : 42
